sudo: required
services:
  - docker

before_install:
  - docker build -t saezbaldo/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true saezbaldo/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-493320227173"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"