sudo: required
services:
  - docker

before_install:
  - docker build -t saezbaldo/docker-react -f Dockerfile.dev.travis .

script:
  - docker run -e CI=true saezbaldo/docker-react npm run test